### ISSUE TITLE
Monitor package archivals

### ISSUE THREAD

**Issue by Bisaloo** [cran-task-views/Epidemiology#14]

**Comment by Bisaloo** [comment]
@zeileis, #8 makes me think you already have a system in place to monitor archivals. Is this the case or is there value in rolling out my own via GitHub Actions?

**Comment by zeileis** [comment]
Yes, the CRAN team supports the task view maintainers in this regard. See also the explanation in the recently added [Maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md#CRAN-package-archivals). It's sufficient to just follow that workflow. But of course, you can set up something in addition to it, if you prefer.

**Comment by Bisaloo** [comment]
Thanks, the maintenance guidelines are very clear and very helpful!

I think relying on the standard CRAN & CTV process is a good option for now. It strikes a good balance between keeping the task view up-to-date and keeping the number of alerts low.

**Comment by zeileis** [comment]
Great, I agree. Let's see how well the current workflow works in practice. If you have suggestions for improvement, always feel free to get in touch.
