### ISSUE TITLE
Add AMR package for microbial epidemiology 

### ISSUE THREAD

**Issue by msberends** [cran-task-views/Epidemiology#6]
Hi!

I would suggest to add the quite popular AMR package, used in many countries to analyse antimicrobial resistance data to help curbing this major global health threat. 

On CRAN here: https://cran.r-project.org/web/packages/AMR/index.html
Website here: https://msberends.github.io/AMR/

Many thanks!

**Comment by Bisaloo** [comment]
Hi @msberends, thanks for your suggestion! 

Do you have a specific idea of under which section you would add this package? Maybe [in the "Other data packages" section](https://github.com/cran-task-views/Epidemiology/blob/main/Epidemiology.md#other-data-packages)?

**Comment by msberends** [comment]
Yes, that could be an option. “Helpers” also seems to fit if I read the description of that section. 

Would be awesome to see it included! Our package was accepted for publication in JSS, we just finished the copy-editing phase last week so it will be published soon.

**Comment by msberends** [comment]
That’s 😍😍😍
