### ISSUE TITLE
Package 'R0' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Epidemiology#8]
Package [R0](https://CRAN.R-project.org/package=R0) is currently listed in CRAN Task View [Epidemiology](https://CRAN.R-project.org/view=Epidemiology) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by Bisaloo** [comment]
Thanks for letting us know! We'll reach out to the authors and offer to help to get it back on CRAN.

**Comment by tobadia** [comment]
Hi there,

First, thanks for the initiative. For odd reasons, I do receive occasional R-maintainer checks on my gmail, but either I missed the notice of archiving or it wasn't sent to the right place (@Bisaloo mentioned there might still be a very old institutional e-mail listed, that I still have access too but only open every 29th of Feb, so to speak). The suggested fixes have been implemented.

I would like to have a proper implementation pipeline set between the master branche of the GitHub repo and CRAN. Is that an option ?

In the upcoming weeks I plan to take time to thoroughly revamp the package as it needs a very overdue refresh. But I need to make time for this, there are many aspects that could and should be optimized here.

Thanks !

**Comment by Bisaloo** [comment]
What you are describing sounds exactly like [R-universe](https://r-universe.dev/).

It is distinct from CRAN and is provided by [rOpenSci](https://ropensci.org/). It provides a direct pipeline from your `main` branch (or alternatively, any other branch, or the latest release) to a 'CRAN-like' server. Users can install packages from r-universe with the following command:

```r
install.packages("R0", repos = c("https://todabia.r-universe.dev", "https://cloud.r-project.org"))
```

The benefit over installing from GitHub is that users don't need an extra package (`remotes` or `devtools`), and packages are pre-compiled for windows and macOS (as on CRAN). This means that windows users won't have to deal with Rtools for packages that include C/C++ code.

R-universe can also serve as a very simple continuous integration service as it will run R CMD build on every push.

Note that this doesn't replace CRAN, nor does it aim to. CRAN packages are still usually easier to discover and install for novice R users, and CRAN provides an extensive testing infrastructure including reverse dependencies.

- [Official R-universe help page](https://github.com/r-universe-org/help#readme)
- [Example of an R-universe: the tidyverse r-universe](https://tidyverse.r-universe.dev/ui#packages)
